version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    env_file:
      - .env         # Load environment variables
    command: flask run --host=0.0.0.0 --port=5000  # Force Flask to bind to 0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis        # Ensure Redis starts before the Flask app

  worker:
    build: .
    env_file:
      - .env         # Load environment variables
    command: ["python", "worker.py"]  # Run the worker script
    depends_on:
      - redis        # Ensure Redis starts before the worker
    environment:  
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose Redis on port 6379
