version: '3.8'

services:
  flask_docker:
    build: 
      context: .     
    stop_signal: SIGINT
    ports:
      - "5001:5001"  # Map container port 8000 to host port 8000
    env_file:
      - .env         # Load environment variables
    # command: flask run --host=0.0.0.0 --port=5000  # Force Flask to bind to 0.0.0.0
    command: /usr/local/bin/gunicorn -w 2 -b 0.0.0.0:5001 app:app
    # command: >
    #   gunicorn -c "python:config.gunicorn" --reload "flask_docker.app:create_app()"
    # environment:
    #   - FLASK_APP=app.py
    #   - FLASK_RUN_HOST=0.0.0.0
    #   - FLASK_RUN_PORT=5000
    #   - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis        # Ensure Redis starts before the Flask app
    network_mode: "host"


  worker:
    build: .
    env_file:
      - .env         # Load environment variables
    command: ["python", "worker.py"]  # Run the worker script
    depends_on:
      - redis        # Ensure Redis starts before the worker
    # environment:  
    #   - REDIS_URL=redis://redis:6379/0


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose Redis on port 6379
