name: Deploy to Railway

on:
  push:
    branches:
      - Railway_CI_CD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for Railway CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Web Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service web --detach

      - name: Deploy Worker Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service worker --detach

      # Optionally, deploy Redis if needed:
      - name: Deploy Redis Service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service redis --detach
